### ISSUE TITLE
put on pypi

### ISSUE THREAD

**Issue by flying-sheep** [revolunet/python-desktop#1]
you should ask the author of the original package if you can take it over

**Comment by revolunet** [comment]
this is 5 years old so not relevant anymore

**Comment by flying-sheep** [comment]
what’s the modern alternative then?

**Comment by revolunet** [comment]
i have no idea sorry, maybe check https://pypi.org/search/?q=desktop

**Comment by flying-sheep** [comment]
OK, maybe you should archive this repo if it’s old and unmaintained.
